name: sound-edition-indexer
contracts:
- name: SoundCreatorV2
  handler: src/EventHandlers.ts
  events:
  - event: Created(address indexed implementation, address indexed edition, address indexed owner, bytes initData, address[] contracts, bytes[] data, bytes[] results)
networks:
- id: 1
  start_block: 0
  contracts:
  - name: SoundCreatorV2
    address:
    - '0x0000000000aec84F5BFc2af15EAfb943bf4e3522'
- id: 10
  start_block: 0
  contracts:
  - name: SoundCreatorV2
    address:
    - '0x0000000000aec84F5BFc2af15EAfb943bf4e3522'
- id: 8453
  start_block: 0
  contracts:
  - name: SoundCreatorV2
    address:
    - '0x0000000000aec84F5BFc2af15EAfb943bf4e3522'
