name: sound-edition-indexer
contracts:
- name: SoundCreatorV2
  handler: src/EventHandlers.ts
  events:
  - event: Created(address indexed implementation, address indexed edition, address indexed owner, bytes initData, address[] contracts, bytes[] data, bytes[] results)
networks:
- id: 1
  rpc_config:
    url: https://eth-mainnet.g.alchemy.com/v2/XgC6DWhR5QA4gMSdjswAIg15F3G-H7hS
  start_block: 0
  contracts:
  - name: SoundCreatorV2
    address:
    - '0x0000000000aec84F5BFc2af15EAfb943bf4e3522'
- id: 10
  rpc_config:
    url: https://opt-mainnet.g.alchemy.com/v2/MflD-Wlm3AGdMrt44KjHaX6PiVhX91W3
  start_block: 0
  contracts:
  - name: SoundCreatorV2
    address:
    - '0x0000000000aec84F5BFc2af15EAfb943bf4e3522'
- id: 8453
  rpc_config:
    url: https://base-mainnet.g.alchemy.com/v2/3m9vR6Vx1Yo0NurSa-6r65hGwGWzXvEa
  start_block: 0
  contracts:
  - name: SoundCreatorV2
    address:
    - '0x0000000000aec84F5BFc2af15EAfb943bf4e3522'
